### ISSUE TITLE
Blobstore does not seem to have public get access

### ISSUE THREAD

**Issue by cityfarmer** [SAP/service-fabrik-boshrelease#1]
When trying to create the release it fails with an error about accessing the blobstore.  It does not seem as if the S3 (service-fabrik-boshrelease) blobstore has been granted public get access.  

ubuntu@ip-10-100-4-35:/mnt/workspace/boshreleases/service-fabrik-boshrelease-master$ bosh create release --force
Syncing blobs...
golang/go1.6.2.linux-amd64.tar.gz downloading 80.9M (0%)
/var/lib/gems/2.3.0/gems/blobstore_client-1.3262.24.0/lib/blobstore_client/simple_blobstore_client.rb:44:in `get_file': Could not fetch object, 403/ (Bosh::Blobstore::BlobstoreError)

Thanks,
Clinton

**Comment by akskap** [comment]
@cityfarmer Sorry that din't work. We are in the process of updating our broker and boshrelease repositories with latest code, which should be available sometime next month.

To answer your question:

You can use the following settings in your final.yml file
```
---  
final_name: service-fabrik  
blobstore:  
  provider: s3  
  options:  
    region: eu-west-1  
    bucket_name: service-fabrik-test  
    endpoint: https://s3-eu-west-1.amazonaws.com
```  

Please note that the blobstore referenced here 'will change' as part of the code updates due next month and should not be considered something final.

Thanks,
Akshay
